# Generated by Django 2.2 on 2022-04-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220413_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipinfor',
            options={'verbose_name_plural': 'ShipInfor'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
